baseurl: https://sicam.com.br/
title: III SICAM
theme: hugo-universal-theme
languageCode: pt-br
defaultContentLanguage: "pt-br"
#disqusShortname: devcows # MUDAR
googleAnalytics: ''
paginate: 5
menu:
  main:
    - identifier: home
      name: Página Inicial
      url: /
      weight: 1
    - identifier: evento
      name: Sobre o evento
      url: #
      weight: 2
    - parent: evento
      name: Sobre o III SICAM
      url: /sobre-o-evento/
      weight: 1
    - parent: evento
      name: Programação Completa
      url: /programacao_completa/
      weight: 2
    - parent: evento
      name: Anais
      url: /anais-iii-sicam.pdf
      weight: 3
    - parent: evento
      name: Facilitação Gráfica
      url: /facilitacao-grafica/
      weight: 3
    - parent: evento
      name: Eixos Temáticos
      url: /eixos-tematicos/
      weight: 4
    # - identifier: blog
    #   name: Notícias
    #   url: /blog/
    #   weight: 4
    # - identifier: inscricao
    #   name: Inscrição
    #   url: https://forms.gle/sew1gi3Bojd2RVEu7
    #   weight: 4
    - parent: evento
      name: Equipe
      url: /equipe/
      weight: 4
    - parent: evento
      name: Submissão de trabalhos
      url: /submissao/
      weight: 4
    - identifier: submissao
      name: Submissão
      url: /submissao/
      weight: 2
    - parent: evento
      name: Edições Anteriores
      url: /edicoes-anteriores/
      weight: 5
    - identifier: faq
      name: FAQ
      url: /faq/
      weight: 3



  topbar:
    - name: Instagram
      pre: <i class='fab fa-2x fa-instagram'></i>
      url: https://www.instagram.com/sicam_procam_usp/
      weight: 2
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: https://www.facebook.com/iii.sicam.2021
      weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: https://twitter.com/sicam_procamusp
      weight: 3
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url:  mailto:iii.sicam.2021@gmail.com
      weight: 4
    - name: Youtube
      pre: <i class='fab fa-2x fa-youtube'></i>
      url: https://www.youtube.com/channel/UCHzIFGixQBeL2zvAdo35O7A/featured
      weight: 1
params:
  about_us: <p>O SICAM tem como principal objetivo promover a integração das diferentes temáticas de pesquisas do PROCAM, assim como, promover um diálogo interdisciplinar que  rege a Ciência Ambiental com  os diversos profissionais que atuam nessa área do conhecimento.  </p>
  address: "<p class=\"text-uppercase\"><strong>Email:</strong> <a href='mailto:iii.sicam.2021@gmail.com'>iii.sicam.2021@gmail.com</a> <br> <strong>Endereço:</strong> <Br><a href='http://www.iee.usp.br/' target='_blank'>Instituto de Energia e Ambiente - Universidade de São Paulo</a> <br> Av. Prof. Luciano Gualberto, 1289 - Butantã, São Paulo - SP, 05508-010</p>"
  author: III SICAM
  carousel:
    enable: yes
  clients:
    enable: yes
    subtitle: ''
    title: Realização
  contact_form_ajax: no
  copyright: Copyright (c) 2021, III SICAM; todos os direitos reservados.
  date_format: 2 de January de 2006
  default_sharing_image: img/Logo_cor.png
  defaultDescription: III Simpósio Interdisciplinar de Ciência Ambiental
  defaultKeywords:
    - SICAM
    - PROCAM
    - IEE
    - USP
  enableGoogleMaps: yes
  facebook_site: ''
  features:
    enable: yes
  logo: img/logo.png
  logo_small: img/logo-small.png
  mainSections: blog
  recent_posts:
    enable: yes
    subtitle:
    title: Notícias
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: Clique aqui
    link_url: 'https://www.youtube.com/channel/UCHzIFGixQBeL2zvAdo35O7A/videos'
    subtitle: Confira os vídeos do evento!
    title: Inscrições encerradas!
  style: green
  testimonials:
    enable: yes
    subtitle:
    title: Eixos Temáticos
  topbar:
    enable: true
    text: ""
  twitter_site: sicam_procamusp
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
