baseurl: https://sicam.netlify.app/
title: III SICAM
theme: hugo-universal-theme
languageCode: pt-br
defaultContentLanguage: "pt-br"
disqusShortname: devcows # MUDAR
googleAnalytics: ''
paginate: 5
menu:
  main:
    - identifier: home
      name: Página Inicial
      url: /
      weight: 1
    - identifier: blog
      name: Notícias
      url: /blog/
      weight: 2
    - identifier: equipe
      name: Equipe
      url: /equipe/
      weight: 3
  topbar:
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/devcows/hugo-universal-theme
      weight: 1
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: http://facebook.com
      weight: 2
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com
      weight: 3
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:your@email.com
      weight: 4
params:
  about_us: <p>Pellentesque habitant morbi tristique senectus et netus et malesuada
    fames ac turpis egestas.</p>
  address: "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\n        <br>13/25
    New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>England\n
    \       <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
  author: DevCows
  carousel:
    enable: yes
  clients:
    enable: yes
    subtitle: ''
    title: Apoio
  contact_form_ajax: no
  copyright: Copyright (c) 2021, III SICAM; todos os direitos reservados.
  date_format: 2 de January de 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: III Simpósio Interdisciplinar de Ciência Ambiental
  defaultKeywords:
    - devows
    - hugo
    - go
  enableGoogleMaps: yes
  facebook_site: ''
  features:
    enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    subtitle:
    title: Notícias
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: Saiba mais
    link_url: '#'
    subtitle: bla bla bla
    title: Submissões de trabalhos
  style: green
  testimonials:
    enable: yes
    subtitle:
    title: Palestrantes
  topbar:
    enable: false
    text: "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n
      \     <p class=\"hidden-md hidden-lg\"><a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\n      <a href=\"#\" data-animate-hover=\"pulse\"><i
      class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
  twitter_site: GoHugoIO
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
