baseurl: https://sicam.com.br/
title: IV SICAM
theme: hugo-universal-theme
languageCode: pt-br
defaultContentLanguage: "pt-br"
#disqusShortname: devcows # MUDAR
googleAnalytics: ''
paginate: 5
menu:
  main:
    - identifier: home
      name: Página Inicial
      url: /
      weight: 1
    # - identifier: blog
    #   name: Notícias
    #   url: /blog/
    #   weight: 2
    - identifier: evento
      name: Evento
      url: #
      weight: 2
    - parent: evento
      name: Sobre o IV SICAM
      url: /sobre-o-evento/
      weight: 1
    - parent: evento
      name: Programação
      url: /programacao/
      weight: 2

    - parent: evento
      name: Grupos Temáticos
      url: /grupos-tematicos/
      weight: 4
    # - identifier: blog
    #   name: Notícias
    #   url: /blog/
    #   weight: 4
    - identifier: inscricao
      name: Inscrição
      url: https://docs.google.com/forms/d/e/1FAIpQLSf3YTizMCqrKLIf9kHC7kUxH1_OX6kPDQ2lKkKN4CJGatIHSQ/viewform
      weight: 4
    - parent: evento
      name: Equipe
      url: /equipe/
      weight: 4
    - parent: evento
      name: Submissão de trabalhos
      url: /submissao/
      weight: 4
    - identifier: submissao
      name: Submissão
      url: /submissao/
      weight: 2
    - parent: ed-anteriores
      name: Edições Anteriores
      url: /edicoes-anteriores/
      weight: 5
    - parent: ed-anteriores
      name: Anais - III SICAM
      url: /anais-iii-sicam.pdf
      weight: 6
    - parent: ed-anteriores
      name: Facilitação Gráfica - III SICAM
      url: /facilitacao-grafica/
      weight: 7
    - parent: ed-anteriores
      name: Vídeos - III SICAM
      url: https://www.youtube.com/channel/UCHzIFGixQBeL2zvAdo35O7A/videos
      weight: 8

    - identifier: ed-anteriores
      name: Edições anteriores
      url: #
      weight: 4
    # - identifier: faq
    #   name: FAQ
    #   url: /faq/
    #   weight: 3



  topbar:
    - name: Instagram
      pre: <i class='fab fa-2x fa-instagram'></i>
      url: https://www.instagram.com/sicam_procam_usp/
      weight: 2
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: https://www.facebook.com/iii.sicam.2021
      weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: https://twitter.com/sicam_procamusp
      weight: 3
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url:  mailto:sicam.iee.usp@gmail.com
      weight: 4
    - name: Youtube
      pre: <i class='fab fa-2x fa-youtube'></i>
      url: https://www.youtube.com/channel/UCHzIFGixQBeL2zvAdo35O7A/featured
      weight: 1
params:
  about_us: <p>O SICAM tem como principal objetivo promover a integração das diferentes temáticas de pesquisas do PROCAM, assim como, promover um diálogo interdisciplinar que  rege a Ciência Ambiental com  os diversos profissionais que atuam nessa área do conhecimento.  </p>
  address: "<p class=\"text-uppercase\"><strong>Email:</strong> <a href='mailto:sicam.iee.usp@gmail.com'>sicam.iee.usp@gmail.com</a> <br> <strong>Endereço:</strong> <Br><a href='http://www.iee.usp.br/' target='_blank'>Instituto de Energia e Ambiente - Universidade de São Paulo</a> <br> Av. Prof. Luciano Gualberto, 1289 - Butantã, São Paulo - SP, 05508-010</p>"
  author: IV SICAM
  carousel:
    enable: yes
  clients:
    enable: yes
    subtitle: ''
    title: Realização
  contact_form_ajax: no
  copyright: Copyright (c) 2021-2022, IV SICAM; todos os direitos reservados.
  date_format: 2 de January de 2006
  default_sharing_image: img/logo.png
  defaultDescription: IV Simpósio Interdisciplinar de Ciência Ambiental
  defaultKeywords:
    - SICAM
    - PROCAM
    - IEE
    - USP
  enableGoogleMaps: yes
  facebook_site: ''
  features:
    enable: yes
  logo: img/logo.png
  logo_small: img/logo.png
  mainSections: blog
  recent_posts:
    enable: false
    subtitle:
    title: Notícias
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: "Prazo prorrogado até 25/09/2022!"
    link_url: '/submissao/'
#    subtitle: Submeta o resumo expandido até 04/09/2022!
    title: Submissões abertas!
  style: green
  testimonials:
    enable: false
    subtitle:
    title: Eixos Temáticos
  topbar:
    enable: true
    text: ""
  twitter_site: sicam_procamusp
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
